## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
new_columns = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL']
clean_df = application_df[new_columns].copy()
clean_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
print(clean_df.nunique(axis=0))

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = clean_df.value_counts('APPLICATION_TYPE')
print(app_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace =  app_counts[app_counts <500].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
class_counts = clean_df.value_counts('CLASSIFICATION')
print(class_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2190        1
C2380        1
C2500        1
C2561        1
C8210        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
filt_class_counts = class_counts.loc[class_counts >1]
print(filt_class_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1278       10
C1238       10
C1235        9
C1237        9
C7210        7
C1720        6
C4100        6
C2400        6
C1600        5
C1257        5
C2710        3
C1260        3
C0           3
C1267        2
C1246        2
C1256        2
C3200        2
C1234        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = class_counts[class_counts <1000].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
cols_to_convert = ['USE_CASE', 'INCOME_AMT']
dummy_df = pd.get_dummies(clean_df,columns = cols_to_convert,  prefix=cols_to_convert)
dummy_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,ORGANIZATION,STATUS,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,USE_CASE_CommunityServ,USE_CASE_Heathcare,...,USE_CASE_ProductDev,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,T10,Independent,C1000,Association,1,N,5000,1,False,False,...,True,True,False,False,False,False,False,False,False,False
1,T3,Independent,C2000,Co-operative,1,N,108590,1,False,False,...,False,False,True,False,False,False,False,False,False,False
2,T5,CompanySponsored,C3000,Association,1,N,5000,0,False,False,...,True,True,False,False,False,False,False,False,False,False
3,T3,CompanySponsored,C2000,Trust,1,N,6692,1,False,False,...,False,False,False,True,False,False,False,False,False,False
4,T3,Independent,C1000,Trust,1,N,142590,1,False,True,...,False,False,False,False,True,False,False,False,False,False

In [ ]:
# Split our preprocessed data into our features and target arrays
X = dummy_df[['USE_CASE_CommunityServ', 'USE_CASE_Heathcare', 'USE_CASE_Other', 'USE_CASE_Preservation', 'USE_CASE_ProductDev', 'INCOME_AMT_0', 'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999', 'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
            'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M' ]]
y = dummy_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# Add the input layer
nn.add(tf.keras.layers.Input(shape=(X_train_scaled.shape[1],)))

# First hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation='relu', input_dim=14))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation='relu', input_dim=14))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 5)                 75

 dense_4 (Dense)             (None, 5)                 30

 dense_5 (Dense)             (None, 1)                 6

=================================================================
Total params: 111 (444.00 Byte)
Trainable params: 111 (444.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Train the model
fit_nn = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 3ms/step - loss: 0.7009 - accuracy: 0.5360
Epoch 2/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6869 - accuracy: 0.5444
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6855 - accuracy: 0.5462
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6852 - accuracy: 0.5466
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6850 - accuracy: 0.5468
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6847 - accuracy: 0.5480
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6847 - accuracy: 0.5484
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6846 - accuracy: 0.5484
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6847 - accuracy: 0.5485
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6846 - accuracy: 0.5484
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6846 - accuracy: 0.5483
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6846 - accuracy: 0.5484
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5485
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5485
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5484
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5485
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6845 - accuracy: 0.5485
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5485
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5485
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5485
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5484
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5485
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5485
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5483
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6845 - accuracy: 0.5485
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5485
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6843 - accuracy: 0.5486
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6843 - accuracy: 0.5486
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5486
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6844 - accuracy: 0.5484
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5486
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5486

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6860 - accuracy: 0.5441 - 401ms/epoch - 1ms/step
Loss: 0.6860014796257019, Accuracy: 0.5441399216651917

In [21]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.hf')